authorName: Onepanel, Inc.
experimentName: MNIST TF v2.x
trialConcurrency: 1
maxExecDuration: 1h
maxTrialNum: 10
trainingServicePlatform: local
searchSpacePath: search_space.json
useAnnotation: false
tuner:
  # gpuIndices: '0'           # uncomment and update to the GPU indices to assign this tuner
  builtinTunerName: TPE       # choices: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
  classArgs:
    optimize_mode: maximize   # choices: maximize, minimize
trial:
  command: python main.py --output /mnt/output
  codeDir: .
  # gpuNum: 1                 # uncomment and update number to number of GPUs